platform:
    - x86
    - x64

environment:
    matrix:
        - VSVER: 15

configuration:
    - plain
    - shared

matrix:
    allow_failures:
        - platform: x64
          VSVER: 9
        - platform: x64
          VSVER: 10
        - platform: x64
          VSVER: 11

before_build:
    - ps: >-
        If ($env:Platform -Match "x86") {
            $env:VCVARS_PLATFORM="x86"
            $env:TARGET="VC-WIN32"
            $env:DO="do_ms"
        } Else {
            $env:VCVARS_PLATFORM="amd64"
            $env:TARGET="VC-WIN64A"
            $env:DO="do_win64a"
        }
    - ps: >-
        If ($env:Configuration -Like "*shared*") {
            $env:MAK="ntdll.mak"
        } Else {
            $env:MAK="nt.mak"
        }
    - ps: >-
        If ($env:VSVER -Match "15") {
            $env:VSCOMNTOOLS=("C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools")
            $env:VSVARSBAT_LOC=($env:VSCOMNTOOLS+"\..\..\VC\Auxiliary\vcvarsall.bat")
        } Else {
            $env:VSCOMNTOOLS=(Get-Content ("env:VS" + "$env:VSVER" + "0COMNTOOLS"))
            $env:VSVARSBAT_LOC=($env:VSCOMNTOOLS+"\..\..\VC\vcvarsall.bat")
        }
    - call "%VSVARSBAT_LOC%" %VCVARS_PLATFORM%
    - perl Configure %TARGET% no-asm
    - call ms\%DO%

build_script:
    - nmake /f ms\%MAK%

test_script:
    - nmake /f ms\%MAK% test
