platform:
    #- x86
    - x64

environment:
    matrix:
        #- VSVER: 14
        - VSVER: 15

configuration:
    - plain-debug
    - plain-release
    #- shared-debug
    #- shared-release

image: Visual Studio 2017

clone_depth: 40

skip_tags: true

before_build:
    - ps: >-
        If ($env:Platform -Match "x86") {
            $env:VCVARS_PLATFORM="x86"
            $env:TARGET="VC-WIN32"
        } Else {
            $env:VCVARS_PLATFORM="amd64"
            $env:TARGET="VC-WIN64A"
        }
    - ps: >-
        If ($env:Configuration -Match "shared") {
            $env:SHARED=""
        } Else {
            $env:SHARED="no-shared"
        }
    - ps: >-
        If ($env:Configuration -Match "debug") {
            $env:RELEASE_TYPE="--debug"
        } Else {
            $env:RELEASE_TYPE="--release"
        }
    - ps: >-
        If ($env:VSVER -Match "15") {
            $env:VSCOMNTOOLS=("C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools")
            $env:VCVARSBAT_LOC=($env:VSCOMNTOOLS+"\..\..\VC\Auxiliary\Build\vcvarsall.bat")
        } Else {
            $env:VSCOMNTOOLS=(Get-Content ("env:VS" + "$env:VSVER" + "0COMNTOOLS"))
            $env:VCVARSBAT_LOC=($env:VSCOMNTOOLS+"\..\..\VC\vcvarsall.bat")
        }
    - call "%VCVARSBAT_LOC%" %VCVARS_PLATFORM%
    - mkdir _build
    - cd _build
    - perl ..\Configure %TARGET% no-asm %SHARED% %RELEASE_TYPE%
    - cd ..

build_script:
    - cd _build
    - nmake
    - cd ..

after_build:
    - ps: $env:ARTIFACT_ZIP_BASE_NAME=($env:APPVEYOR_REPO_BRANCH+"-"+$env:Configuration+"-"+$env:Platform+"-vc"+$env:VSVER+"-build_"+$env:APPVEYOR_BUILD_VERSION)

test_script:
    - cd _build
    - nmake test
    - mkdir ..\_install
    - nmake install install_docs DESTDIR=..\_install
    - cd ..

artifacts:
    - path: '_build'
      name: '$(ARTIFACT_ZIP_BASE_NAME)-raw-_build'
    - path: '_install'
      name: '$(ARTIFACT_ZIP_BASE_NAME)-raw-_install'
