platform:
    #- x86
    - x64

environment:
    matrix:
        #- VSVER: 9
        #- VSVER: 10
        #- VSVER: 11
        #- VSVER: 12
        #- VSVER: 14
        - VSVER: 15

configuration:
    - plain-debug
    - plain-release
    - shared-debug
    - shared-release

image: Visual Studio 2017

clone_depth: 40

skip_tags: true

matrix:
    allow_failures:
        - platform: x64
          VSVER: 9
        - platform: x64
          VSVER: 10
        - platform: x64
          VSVER: 11

before_build:
    - ps: >-
        If ($env:Platform -Match "x86") {
            $env:VCVARS_PLATFORM="x86"
            If ($env:Configuration -Like "*debug*") {
                $env:TARGET="debug-VC-WIN32"
            } Else {
                $env:TARGET="VC-WIN32"
            }
            $env:DO="do_ms"
        } Else {
            $env:VCVARS_PLATFORM="amd64"
            If ($env:Configuration -Like "*debug*") {
                $env:TARGET="debug-VC-WIN64A"
            } Else {
                $env:TARGET="VC-WIN64A"
            }
            $env:DO="do_win64a"
        }
    - ps: >-
        If ($env:Configuration -Like "*shared*") {
            $env:MAK="ntdll.mak"
        } Else {
            $env:MAK="nt.mak"
        }
    - ps: >-
        If ($env:VSVER -Match "15") {
            $env:VSCOMNTOOLS=("C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools")
            $env:VCVARSBAT_LOC=($env:VSCOMNTOOLS+"\..\..\VC\Auxiliary\Build\vcvarsall.bat")
        } Else {
            $env:VSCOMNTOOLS=(Get-Content ("env:VS" + "$env:VSVER" + "0COMNTOOLS"))
            $env:VCVARSBAT_LOC=($env:VSCOMNTOOLS+"\..\..\VC\vcvarsall.bat")
        }
    - call "%VCVARSBAT_LOC%" %VCVARS_PLATFORM%
    - perl Configure %TARGET% no-asm
    - call ms\%DO%

build_script:
    - nmake /f ms\%MAK%

test_script:
    - nmake /f ms\%MAK% test

after_build:
    - ps: >-
        If ($env:Configuration -Like "*shared*") {
            If ($env:Configuration -Like "*debug*") {
                $env:OBJ_OUT_PATH="out32dll.dbg"
            } Else {
                $env:OBJ_OUT_PATH="out32dll"
            }
        } Else {
            If ($env:Configuration -Like "*debug*") {
                $env:OBJ_OUT_PATH="out32.dbg"
            } Else {
                $env:OBJ_OUT_PATH="out32"
            }
        }
    - ps: $env:INCLUDE_OUT_PATH="inc32"
    - ps: >-
        If ($env:Configuration -Like "*shared*") {
            If ($env:Configuration -Like "*debug*") {
                $env:TMP_OUT_PATH="tmp32dll.dbg"
            } Else {
                $env:TMP_OUT_PATH="tmp32dll"
            }
        } Else {
            If ($env:Configuration -Like "*debug*") {
                $env:TMP_OUT_PATH="tmp32.dbg"
            } Else {
                $env:TMP_OUT_PATH="tmp32"
            }
        }
    - ps: $env:ARTIFACT_ZIP_BASE_NAME=($env:APPVEYOR_REPO_BRANCH+"-"+$env:Configuration+"-"+$env:Platform+"-vc"+$env:VSVER+"-build_"+$env:APPVEYOR_BUILD_VERSION)
    - ps: $env:ARTIFACT_ZIP_MIN_NAME=($env:ARTIFACT_ZIP_BASE_NAME+".zip")
    - ps: $env:ARTIFACT_ZIP_ALL_NAME=($env:ARTIFACT_ZIP_BASE_NAME+"-all.zip")
    - ps: $env:ARTIFACT_ZIP_RAW_OUT_NAME=($env:ARTIFACT_ZIP_BASE_NAME+"-raw-out")
    - ps: $env:ARTIFACT_ZIP_RAW_TMP_NAME=($env:ARTIFACT_ZIP_BASE_NAME+"-raw-tmp")
    - perl util\create_artifact_archives_win32.pl

artifacts:
    - path: '$(ARTIFACT_ZIP_MIN_NAME)'
      name: '$(ARTIFACT_ZIP_MIN_NAME)'
      type: Zip
    - path: '$(ARTIFACT_ZIP_ALL_NAME)'
      name: '$(ARTIFACT_ZIP_ALL_NAME)'
      type: Zip
    - path: '$(OBJ_OUT_PATH)'
      name: '$(ARTIFACT_ZIP_RAW_OUT_NAME)'
    - path: '$(TMP_OUT_PATH)'
      name: '$(ARTIFACT_ZIP_RAW_TMP_NAME)'
